-- Step 1: Clear all existing prompt templates to ensure a clean slate.
DELETE FROM public.prompt_templates;

-- Step 2: Insert a full, optimized set of 12 templates for each of the 5 industries.
INSERT INTO public.prompt_templates (category, name, prompt_template, description, is_active, industry)
VALUES
-- Industry: Food & Beverage (f_b) - 12 Prompts
('display', 'F&B Studio Shot', 'A professional studio product photo of {product} on a clean white background, high resolution, appetizing lighting that highlights freshness and texture, food photography style, sharp details, no distractions, 8k quality.', 'Ảnh studio nền trắng, tập trung vào sự tươi ngon và chi tiết của sản phẩm.', true, 'f_b'),
('display', 'F&B Macro Texture', 'A detailed macro shot of {product}, focusing on its delicious texture (e.g., juicy, crispy, creamy). Use dramatic lighting to create depth. Clean, simple background. High-end food photography.', 'Ảnh cận cảnh làm nổi bật kết cấu hấp dẫn của món ăn.', true, 'f_b'),
('display', 'F&B Minimalist Flat-lay', 'A minimalist top-down flat-lay of {product} on a clean, contrasting surface. Styled with one or two simple, relevant ingredients. Balanced composition, soft natural light. Modern and clean.', 'Ảnh flat-lay tối giản từ trên xuống, bố cục sạch sẽ và hiện đại.', true, 'f_b'),
('model', 'F&B Lifestyle Dining', 'A lifestyle photo of a diverse model enjoying {product} in a cozy cafe or restaurant setting. Natural lighting, mouthwatering food styling, focus on the happy experience of eating. Professional food photography.', 'Người mẫu đang thưởng thức sản phẩm trong bối cảnh quán ăn, tạo cảm giác ngon miệng.', true, 'f_b'),
('model', 'F&B Hands-in-Frame', 'A dynamic "hands-in-frame" shot, showing hands preparing or serving {product} (e.g., pouring sauce, slicing). Focus on the action and the delicious result. Bright, clean lighting.', 'Ảnh cận cảnh tay đang chuẩn bị hoặc thưởng thức món ăn, tạo cảm giác sống động.', true, 'f_b'),
('model', 'F&B Chef''s Touch', 'A professional shot of a chef''s hands adding a final touch to {product} in a kitchen environment. The focus is on craftsmanship and quality ingredients. Moody, professional lighting.', 'Đầu bếp đang hoàn thiện món ăn, nhấn mạnh sự chuyên nghiệp và chất lượng.', true, 'f_b'),
('social', 'F&B Vibrant Table Scene', 'A vibrant social media post featuring {product} as part of a beautiful table scene. Engaging composition with drinks and side dishes. Bright, cheerful colors, high resolution, Instagram-ready food blogger style.', 'Bối cảnh bàn ăn đầy màu sắc, phù hợp cho bài đăng mạng xã hội.', true, 'f_b'),
('social', 'F&B Action Shot', 'An eye-catching action shot for social media, like {product} being drizzled with syrup or cheese being pulled. Dynamic, stop-scrolling content. Sharp focus on the action.', 'Ảnh hành động (VD: rót sốt), tạo hiệu ứng thị giác mạnh mẽ.', true, 'f_b'),
('social', 'F&B Seasonal Theme', 'A social media photo of {product} styled with a seasonal theme (e.g., summer picnic, cozy winter). Use relevant props and colors to evoke the feeling of the season. Engaging and festive.', 'Sản phẩm được trang trí theo chủ đề mùa lễ hội, tạo cảm giác gần gũi.', true, 'f_b'),
('seeding', 'F&B Customer Review', 'A user-generated content style photo of {product} on a table at a restaurant, taken from a customer''s perspective. Casual handheld shot, natural lighting, looks like an authentic customer review on social media.', 'Ảnh chụp từ góc nhìn khách hàng, tạo cảm giác chân thực như một bài review.', true, 'f_b'),
('seeding', 'F&B Home Cooking', 'An authentic photo of {product} being enjoyed at home, perhaps on a kitchen counter or dining table. Looks like a real person made or is eating it. Warm, natural home lighting.', 'Sản phẩm trong bối cảnh nhà bếp hoặc bữa ăn tại nhà, tạo sự gần gũi.', true, 'f_b'),
('seeding', 'F&B Street Food Vibe', 'A casual, vibrant photo of {product} being held and eaten outdoors, street food style. The background is slightly blurred. Looks like a fun, authentic food discovery.', 'Cảm giác như đang thưởng thức món ăn đường phố, tự nhiên và sống động.', true, 'f_b'),

-- Industry: Beauty & Personal Care (beauty) - 12 Prompts
('display', 'Beauty Product on Marble', 'A professional beauty product photo of {product} on an elegant white or pink marble background. High resolution, soft natural lighting, clean and minimal composition, focus on luxury packaging.', 'Ảnh sản phẩm trên nền đá marble sang trọng, ánh sáng mềm mại.', true, 'beauty'),
('display', 'Beauty Texture Smear', 'A macro shot of the texture of {product} smeared on a clean surface. Show the creaminess, gloss, or particles. Soft, clean lighting. Highlights the sensory experience of the product.', 'Ảnh cận cảnh kết cấu sản phẩm (kem, gel) để thể hiện chất liệu.', true, 'beauty'),
('display', 'Beauty Minimalist Group', 'A minimalist shot of {product} arranged with one or two other products from the same line. Clean, geometric composition on a solid pastel background. Modern and chic.', 'Sản phẩm được sắp xếp tối giản cùng các món đồ khác, tạo cảm giác hiện đại.', true, 'beauty'),
('model', 'Beauty Skin Application', 'A close-up lifestyle photo of a diverse model applying {product} to their glowing skin (e.g., face, hand). Soft, natural lighting that emphasizes healthy skin. Professional beauty photography.', 'Người mẫu đang thoa sản phẩm lên da, nhấn mạnh làn da khỏe mạnh.', true, 'beauty'),
('model', 'Beauty Product in Hand', 'An elegant shot of a model''s hand with perfect manicure holding {product}. The background is clean and slightly blurred. Focus on the luxury feel of holding the product.', 'Bàn tay người mẫu cầm sản phẩm một cách thanh lịch, tạo cảm giác cao cấp.', true, 'beauty'),
('model', 'Beauty Natural Look', 'A portrait of a diverse model with a natural, "no-makeup" makeup look, showcasing the results of using {product}. The setting is bright and airy. Focus on healthy, radiant skin.', 'Chân dung người mẫu với vẻ đẹp tự nhiên, thể hiện hiệu quả của sản phẩm.', true, 'beauty'),
('social', 'Beauty Shelfie', 'A trendy "shelfie" photo for social media, with {product} beautifully arranged on a bathroom shelf with other aesthetic items like plants and candles. Bright, clean, and Instagram-worthy.', 'Sản phẩm được bày trên kệ phòng tắm, phong cách "shelfie" hợp xu hướng.', true, 'beauty'),
('social', 'Beauty Flat-lay with Nature', 'A vibrant beauty flat-lay for social media, featuring {product} surrounded by natural elements like flowers, leaves, or water droplets that relate to its ingredients. Engaging and fresh.', 'Ảnh flat-lay với các yếu tố thiên nhiên, nhấn mạnh thành phần tự nhiên.', true, 'beauty'),
('social', 'Beauty Color Pop', 'An eye-catching social media post with {product} against a bold, single-color background. Use hard light and sharp shadows for a modern, graphic look. Stop-scrolling content.', 'Sản phẩm trên nền một màu sắc nổi bật, tạo hiệu ứng đồ họa mạnh mẽ.', true, 'beauty'),
('seeding', 'Beauty Bathroom Counter', 'A realistic, user-generated content style photo of {product} on a slightly messy but stylish bathroom counter. Natural morning light. Looks like a real person''s daily routine.', 'Ảnh sản phẩm trên bàn trang điểm, tạo cảm giác chân thực như một phần của thói quen hàng ngày.', true, 'beauty'),
('seeding', 'Beauty User Selfie', 'An authentic selfie of a person with great skin, holding up {product} as a recommendation. Casual setting, natural lighting. Looks like a genuine post from a happy customer.', 'Selfie của người dùng cầm sản phẩm, như một lời giới thiệu chân thành.', true, 'beauty'),
('seeding', 'Beauty Unboxing Experience', 'A UGC-style photo of {product} being unboxed. The packaging is visible. The hands holding it look excited. Soft, natural lighting. Creates a sense of anticipation.', 'Ảnh unbox sản phẩm, tạo cảm giác háo hức và chân thực.', true, 'beauty'),

-- Industry: Fashion & Accessories (fashion) - 12 Prompts
('display', 'Fashion Luxury Flat-lay', 'A luxury flat-lay photo of {product}, professionally styled on a clean marble or silk background. Use soft, elegant lighting to highlight texture and premium quality. High resolution, editorial fashion catalog style.', 'Ảnh flat-lay sang trọng trên nền lụa hoặc marble, làm nổi bật chất liệu.', true, 'fashion'),
('display', 'Fashion Ghost Mannequin', 'Professional studio shot of {product} on a ghost mannequin to show its shape and fit perfectly. Clean white background, even lighting, sharp details, ready for e-commerce.', 'Ảnh trên manocanh ẩn, thể hiện rõ phom dáng sản phẩm.', true, 'fashion'),
('display', 'Fashion Macro Detail', 'A detailed macro shot of {product}, focusing on the fabric texture, stitching, and craftsmanship (e.g., a button, a zipper). Use dramatic side lighting to create depth. High-end fashion photography.', 'Ảnh cận cảnh chi tiết đường may, chất liệu vải.', true, 'fashion'),
('model', 'Fashion Editorial Lookbook', 'An editorial fashion photo of a diverse, confident model wearing {product} in a professional studio with a solid color background. Dynamic lighting, powerful pose, emphasizing the product''s style.', 'Người mẫu trong studio với phong cách editorial, tạo dáng mạnh mẽ.', true, 'fashion'),
('model', 'Fashion Street Style', 'A street style photo of a trendy model wearing {product} in a dynamic urban environment. Capture a candid, in-motion pose. Natural lighting. The vibe should be cool, edgy, and fashionable.', 'Người mẫu với phong cách street style trên đường phố, năng động và thời thượng.', true, 'fashion'),
('model', 'Fashion Lifestyle Moment', 'A lifestyle fashion photo featuring {product} in an aspirational setting, like a luxury cafe or a beautiful park. The model looks relaxed and natural. Soft, golden hour lighting.', 'Ảnh lifestyle trong bối cảnh sang trọng, tạo cảm giác gần gũi.', true, 'fashion'),
('social', 'Fashion Minimalist Post', 'A minimalist and chic social media photo featuring {product}. Use a neutral color palette, plenty of negative space, and interesting shadows. Perfect for a high-end Instagram feed.', 'Bố cục tối giản, sang trọng cho bài đăng Instagram.', true, 'fashion'),
('social', 'Fashion "Get The Look"', 'An engaging "Get The Look" style photo for a social media carousel. {product} is the centerpiece, styled with other complementary fashion items. Clean but stylish background.', 'Ảnh "Get The Look", phối sản phẩm với các phụ kiện khác.', true, 'fashion'),
('social', 'Fashion TikTok/Reels Ready', 'An eye-catching, vibrant shot of {product} designed for TikTok or Instagram Reels. Use bold colors, a dynamic angle, and a sense of movement. Modern, energetic, and stop-scrolling.', 'Ảnh đầy năng lượng, màu sắc bắt mắt cho TikTok/Reels.', true, 'fashion'),
('seeding', 'Fashion OOTD', 'An authentic user-generated content (UGC) style photo. A person is showing off their OOTD (outfit of the day) featuring {product}. Natural outdoor lighting, taken with a smartphone, casual and relatable pose.', 'Ảnh OOTD (Outfit of the Day) tự nhiên như người dùng tự chụp.', true, 'fashion'),
('seeding', 'Fashion Mirror Selfie', 'A realistic mirror selfie of a person wearing {product} in a stylish room or fitting room. The lighting is natural and slightly imperfect. The feel is authentic and personal, like a fashion influencer post.', 'Ảnh selfie trước gương, phong cách tự nhiên và chân thật.', true, 'fashion'),
('seeding', 'Fashion Unboxing', 'A UGC-style photo showing the unboxing of {product}. The product is partially out of its beautiful packaging, placed on a bed or a clean floor. Natural, soft lighting. Creates a sense of anticipation.', 'Ảnh unbox sản phẩm, tạo cảm giác háo hức.', true, 'fashion'),

-- Industry: Mother & Baby (mother_baby) - 12 Prompts
('display', 'Baby Product in Nursery', 'A professional baby product photo of {product} styled in a beautiful, soft-focus nursery setting. Gentle, natural lighting from a window. Clean, safe, and serene composition.', 'Sản phẩm trong bối cảnh phòng ngủ em bé, ánh sáng tự nhiên.', true, 'mother_baby'),
('display', 'Baby Product Clean Shot', 'A clean studio shot of {product} on a soft pastel background. Styled with a single, safe baby toy (e.g., a wooden block). Focus on product safety and quality materials.', 'Ảnh studio trên nền pastel, nhấn mạnh sự an toàn và chất lượng.', true, 'mother_baby'),
('display', 'Baby Product Gentle Flat-lay', 'A gentle flat-lay of {product} on a soft, textured blanket. Surrounded by other safe baby essentials. Top-down view, soft and even lighting. Warm and caring feel.', 'Ảnh flat-lay trên chăn mềm, tạo cảm giác ấm áp và dịu dàng.', true, 'mother_baby'),
('model', 'Parent & Baby Moment', 'A warm, lifestyle photo of a parent lovingly using {product} with their baby. A candid, happy moment. Soft, natural lighting. Emphasizes safety, comfort, and bonding.', 'Khoảnh khắc ấm áp giữa cha mẹ và bé khi sử dụng sản phẩm.', true, 'mother_baby'),
('model', 'Baby Using Product', 'A close-up shot of a happy baby safely interacting with {product} (if applicable, e.g., a toy or bottle). The focus is on the baby''s joyful and safe experience. Bright and cheerful lighting.', 'Ảnh cận cảnh em bé đang vui vẻ sử dụng sản phẩm.', true, 'mother_baby'),
('model', 'Family Lifestyle', 'A beautiful photo of a happy family (mother, father, baby) in a bright, clean home setting, with {product} naturally integrated into their life. The mood is loving and peaceful.', 'Sản phẩm trong bối cảnh gia đình hạnh phúc, tạo sự tin tưởng.', true, 'mother_baby'),
('social', 'Parenting Tip Post', 'A social media graphic featuring {product} with space for text. The style is clean, informative, and helpful, suitable for a parenting tip post. Pastel color palette.', 'Ảnh phù hợp cho bài đăng chia sẻ kinh nghiệm, có không gian cho chữ.', true, 'social'),
('social', 'Baby Milestone', 'A photo of {product} styled to celebrate a baby milestone (e.g., 6 months old). Cute and celebratory props. Perfect for Instagram posts targeting new parents.', 'Sản phẩm trong bối cảnh kỷ niệm một cột mốc của bé.', true, 'mother_baby'),
('social', 'Nursery Shelfie', 'A beautifully organized nursery shelf featuring {product} among other stylish baby items. Aesthetically pleasing, clean, and inspirational for parents on social media.', 'Sản phẩm trên kệ trang trí phòng bé, tạo cảm hứng cho cha mẹ.', true, 'mother_baby'),
('seeding', 'Real Mom Review', 'An authentic, UGC-style photo of {product} in a real home setting. Looks like it was taken by a mom to share on a parenting group. Natural lighting, slightly messy background.', 'Ảnh chân thực như một bài review của một bà mẹ.', true, 'mother_baby'),
('seeding', 'Baby''s Daily Life', 'A casual, candid shot of {product} being used in a baby''s daily life (e.g., during playtime, mealtime). Looks like a real photo from a parent''s phone. Warm and relatable.', 'Sản phẩm trong một khoảnh khắc đời thường của bé.', true, 'mother_baby'),
('seeding', 'Parent Recommendation', 'A photo of a parent holding {product} and smiling at the camera, as if recommending it. The setting is a bright, happy home. Trustworthy and authentic feel.', 'Cha mẹ cầm sản phẩm và mỉm cười, như một lời giới thiệu đáng tin cậy.', true, 'mother_baby'),

-- Industry: Other (General) - 12 Prompts
('display', 'General Clean Studio', 'A clean, professional studio shot of {product} on a seamless white or light gray background. Perfect, even lighting that eliminates harsh shadows. Focus on the product''s design and form. 8k, high resolution.', 'Ảnh studio trên nền trắng/xám, ánh sáng đều, làm nổi bật thiết kế.', true, 'other'),
('display', 'General Product in Context', 'A studio shot of {product} on a simple, relevant surface (e.g., a wooden desk for tech, a kitchen counter for an appliance) with a clean, blurred background. Shows the product in its intended environment.', 'Sản phẩm trên một bề mặt liên quan, cho thấy môi trường sử dụng.', true, 'other'),
('display', 'General Floating Product', 'A dynamic shot of {product} appearing to float against a solid, modern color background. Use subtle shadows to create a 3D effect. Highlights the product''s sleekness and innovation.', 'Ảnh sản phẩm "lơ lửng" trên nền màu, tạo cảm giác hiện đại.', true, 'other'),
('model', 'General Lifestyle Use', 'A lifestyle photo of a diverse model happily using {product} in a natural, realistic setting (e.g., home, office). The focus is on the product''s functionality and how it improves daily life.', 'Người mẫu đang sử dụng sản phẩm trong bối cảnh đời thường.', true, 'other'),
('model', 'General Professional Use', 'A photo of a professional (e.g., designer, technician) using {product} in their work environment. Conveys reliability, efficiency, and professional-grade quality.', 'Chuyên gia đang sử dụng sản phẩm, nhấn mạnh tính chuyên nghiệp.', true, 'other'),
('model', 'General Close-up Interaction', 'A close-up shot of a person''s hands interacting with a key feature of {product}. Highlights ease of use and specific functionalities. Clean, focused lighting.', 'Ảnh cận cảnh tay đang tương tác với một tính năng của sản phẩm.', true, 'other'),
('social', 'General Tech Review Style', 'A social media photo styled like a tech review blog. {product} is neatly arranged on a desk with other modern gadgets. Clean, top-down flat-lay. Informative and sleek.', 'Ảnh flat-lay theo phong cách review công nghệ.', true, 'other'),
('social', 'General "How It Works"', 'An engaging social media post that visually explains a feature of {product}. Could use simple graphics or a dynamic composition. Clear, bright, and educational.', 'Ảnh giải thích một tính năng của sản phẩm, mang tính giáo dục.', true, 'other'),
('social', 'General Comparison Shot', 'A split-screen or side-by-side image comparing a feature of {product} to an older version or a competitor (conceptually). Highlights the key benefit. Modern and graphic.', 'Ảnh so sánh tính năng, làm nổi bật ưu điểm.', true, 'other'),
('seeding', 'General Unboxing', 'A realistic, UGC-style photo of {product} being unboxed on a desk or table. The packaging is visible. Looks like a genuine customer photo shared on social media.', 'Ảnh unbox sản phẩm chân thực như khách hàng tự chụp.', true, 'other'),
('seeding', 'General In-Situ', 'An authentic photo of {product} in a real, slightly messy, everyday environment (e.g., on a kitchen counter with other items, on a nightstand). Looks natural and unstaged.', 'Sản phẩm trong một bối cảnh đời thường, không sắp đặt.', true, 'other'),
('seeding', 'General User Testimonial', 'A photo of a happy person looking at the camera, with {product} visible in their environment. The style is like a screenshot from a video testimonial. Trustworthy and relatable.', 'Ảnh như một lời chứng thực từ người dùng hài lòng.', true, 'other');