-- Tạm thời tắt RLS trên các bảng chính để kiểm tra
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.points_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.renders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_follows DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_commissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_payouts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompt_templates DISABLE ROW LEVEL SECURITY;